<?php
/** @var Mtools\MediaManager\Block\Adminhtml\MediaManager $block */
?>
<div class="media-manager-wrapper">
    <?= /* @noEscape */ $block->getMediaButton() ?>

    <script type="text/javascript">
        require([
            'jquery',
            "mage/adminhtml/browser"
        ], function($) {
            $('.media-manager-wrapper button.btn-mediamanager').trigger('click');
        });
    </script>
</div>
